# Generated by Django 3.2.4 on 2021-08-25 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=250)),
                ('dive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dive')),
            ],
        ),
    ]
