# Generated by Django 3.2.4 on 2021-08-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dive',
            name='notes',
        ),
        migrations.AlterField(
            model_name='dive',
            name='number',
            field=models.IntegerField(verbose_name='Dive Number'),
        ),
    ]
