# Generated by Django 3.2.4 on 2021-08-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210825_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='buddies',
            field=models.ManyToManyField(to='main_app.Buddy'),
        ),
    ]
