# Generated by Django 3.2.6 on 2021-08-26 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='location1',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='location2',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='location3',
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
