# Generated by Django 3.2.6 on 2021-08-26 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210826_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.trip'),
        ),
    ]
