# Generated by Django 3.2.6 on 2021-08-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_dive_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dive',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dive',
            name='max_depth',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dive',
            name='site',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dive',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Start Date'),
        ),
    ]
