# Generated by Django 3.2.6 on 2021-08-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210826_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='buddies',
            field=models.ManyToManyField(blank=True, to='main_app.Buddy'),
        ),
    ]
