# Generated by Django 3.2.6 on 2021-08-26 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_dive_buddies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.DateField(default=datetime.date(2021, 8, 26)),
        ),
    ]
