# Generated by Django 3.2.6 on 2021-08-26 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210826_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 26, 23, 3, 59, 120952, tzinfo=utc)),
        ),
    ]
