# Generated by Django 3.2.6 on 2021-08-26 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_note_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 6, 6, 958164, tzinfo=utc)),
        ),
    ]
