# Generated by Django 3.2.6 on 2021-08-26 23:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_note_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buddy',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='buddy',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 12, 4, 317301, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='dive',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 12, 4, 318022, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 12, 4, 320153, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 12, 4, 316683, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 12, 4, 319456, tzinfo=utc)),
        ),
    ]
