# Generated by Django 3.2.6 on 2021-08-26 23:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210826_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 22, 25, 362122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dive',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 22, 25, 362651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 22, 25, 363837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 22, 25, 364300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 23, 22, 25, 361529, tzinfo=utc)),
        ),
    ]
