# Generated by Django 3.2.6 on 2021-08-27 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210827_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 16, 56, 53, 612233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dive',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 16, 56, 53, 612921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 16, 56, 53, 614201, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 16, 56, 53, 614699, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 16, 56, 53, 611562, tzinfo=utc)),
        ),
    ]
