# Generated by Django 3.2.6 on 2021-08-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20210827_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dive',
            name='max_depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max Depth'),
        ),
        migrations.AlterField(
            model_name='dive',
            name='number',
            field=models.IntegerField(verbose_name='Dive #'),
        ),
        migrations.AlterField(
            model_name='dive',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
