# Generated by Django 3.2.6 on 2021-08-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20210828_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dive',
            old_name='max_depth',
            new_name='depth_max',
        ),
        migrations.AddField(
            model_name='dive',
            name='air_choice',
            field=models.CharField(blank=True, choices=[('A', 'Air'), ('N', 'Nitrox')], max_length=1, null=True, verbose_name='Air Choice'),
        ),
        migrations.AddField(
            model_name='dive',
            name='air_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Air End (psi)'),
        ),
        migrations.AddField(
            model_name='dive',
            name='air_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Air Start (psi)'),
        ),
        migrations.AddField(
            model_name='dive',
            name='depth_avg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Average Depth'),
        ),
        migrations.AddField(
            model_name='dive',
            name='geeks_field',
            field=models.TimeField(blank=True, null=True, verbose_name='BIG OLD TEST'),
        ),
        migrations.AddField(
            model_name='dive',
            name='temperature_air',
            field=models.IntegerField(blank=True, null=True, verbose_name='Air Temperature (F))'),
        ),
        migrations.AddField(
            model_name='dive',
            name='temperature_bottom',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bottom Temperature (F))'),
        ),
        migrations.AddField(
            model_name='dive',
            name='temperature_surface',
            field=models.IntegerField(blank=True, null=True, verbose_name='Surface Temperature (F))'),
        ),
        migrations.AddField(
            model_name='dive',
            name='visibility',
            field=models.IntegerField(blank=True, null=True, verbose_name='Visbility (ft))'),
        ),
        migrations.AddField(
            model_name='dive',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight (lb)'),
        ),
        migrations.AddField(
            model_name='dive',
            name='weight_rating',
            field=models.CharField(blank=True, choices=[('E', '✔️'), ('P', '➕'), ('N', '➖')], max_length=1, null=True, verbose_name='Weight Rating'),
        ),
        migrations.AlterField(
            model_name='dive',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dive Site'),
        ),
    ]
