# Generated by Django 3.2.6 on 2021-08-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_remove_dive_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='acc_bottom_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Acc. Bottom Time (min)'),
        ),
    ]
