# Generated by Django 3.2.6 on 2021-08-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_buddy_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(max_length=250),
        ),
    ]
