# Generated by Django 3.2.4 on 2021-08-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_note_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Site'),
        ),
    ]
